### ISSUE TITLE
Better buttons

### ISSUE THREAD

**Issue by arihan01** [arihan01/js-stories#3]
Make the navigation buttons look better, add styling for hovering and active states, etc.

**Comment by Keerthivardhan1** [comment]
bro can I work on this issue

**Comment by Keerthivardhan1** [comment]
bro its seems that there is only one button that is "up" 
I should style it right

**Comment by Keerthivardhan1** [comment]
I am new to the git and github.
can you assign this to me is this issue will be  accepted in hacktoberfest?

**Comment by octosapien** [comment]
@arihan01 
I would love to work on this .
Could you please assign me this issue ?

**Comment by CoderCatA5** [comment]
sure
